# Generated by Django 2.0.3 on 2018-09-17 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 17, 11, 9, 1, 445132), help_text='发布日期', verbose_name='发布日期'),
        ),
    ]
